apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-credential
  namespace: test-pods
spec:
  encryptedData:
    token: AgAXIrxpqdADjDADr3oQncYe+bW7WfTry9bz5j3yKM9g/68PzPa4tse69mHKafH3ZKXgBr+NhJbjF3Y7RjUFH5IBc377hAAxTzaEPoTIVHFaWDCjiHqRpn5xb0VH0g23ZHZhUb3N5t5O4E+7ziyrx/wCpdKlfjStm60SEAL91UXbe6Ao2ifBhpx0Oc5HpJDpVKyUVjQ6R5PM8bsw97A/tRZ0Vbv8Yf3sBzXzN5IrevSWRe4E5w9eHj9fZPWhUPUiyQD5Ad2+HH05X3QMifeAuheUZafn8h4VKtTXTEiKKA6A9UI0IP/O2wdLHZK8+PC2wnJ0g87i5cNH5bsaN2eAaDc92eUYcE9utQipde08dpSEMEHaJX5ZS7xtO2fBi9C/a4zhyy5lkggUlWnrMcVLBBlIiXdUTViXr8q2k2Qt/TJjp1EiCIW7cTcJHd0l2yq0+6I1+/uKE1gJ6G9l8a9GjDAoP47Zvh7Xi8oAJt7XQw9dgFOoTseBF+mWuWgY5HZsvv6vmGyjmCFDRVgFNIcUu7gMuS5LCjnQZQNNI8Kbq6dzjQ01LlTTTwPLw0R+dxI6z/T1xHtef6+4suTdgcjHfIbLVqb+qRHvAFVzm+vt0N6FX9MUDJ4vyvDNoGzWb+duzixfbMLw0rwWCr2cWr4AKCf82zjcltP6cSJdYMYq2ADuxdgTFX8XJwQpKw6pzq5kwL3mo5ZSoXE/ZWScRfw7KCV0vi1O+ogVCQMp0f2jI0dRpTbfitxA64FAcgDouT7W++YMXG3EGdBU/Q==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: slack-credential
      namespace: test-pods

