apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pypi-credential
  namespace: test-pods
spec:
  encryptedData:
    .netrc: AgBFoyscNC5gl9dndBqFL8EGWa2w8MpEcBHJiOo7Lp3UQoHqTOINR3Rbm05FNhiz7q+yVeLAqtpsr5AdZDJvm+2J79JysecDRgl+D/ZUcAvpzSQJy3/9AW7hJR2zYc5nNa6lpiyqhUhOCp3synoCYwqG0GPZkswoDDxW/wv7m6czHeDwKFB4i0ELHS8djRMaB9Gpbow61/Jkr/KvtR6NF/xdft5zm85IrpvPiRlODRbD87KD7l2RyyW8oACfJ1dT1J+w+akLjlvxwNmVqAp17bVWWbd0n2U1DXUpAeuTjHeuX7peMf1WLvrULRJSndiQUKKiIrcB/hm1CgRjHFTfNr7nSxla4hBHS4beju4kjhfIOjE1MI0BSKgDqj86nPNvPqHmiao2oKnCRA0CgfF5GLi6qqVoxTozCrbXbGjRGu4qJZHROsnEt+B+nvtcSwa4LUsElIoB4WG+nceyVGEyPw1l6uYQUVmb+O1GYgpu6suTjHz6i9vBNo4zeuBEaLVG/yrU3B93/a/j1R7CsIrcK/AYpkAZFYPeAKWObMsh963AOxqMs4L9FgNAqfXqVlX+M0Fll+ih353oEdXVj1CdtuAZpvXiS/PkNcS1Lu+Yfs9F3rHtZjB43/NfnXfo9ml6NovZPulzOqtGJhR1yN9juy4JVPj23DNj9CmYwYgKmTT3NySODqmlaXr7ElN7+WBFMq9kKQGBQDOegu3j2gh38TDd/p5ZcATXjwPyI9G3nV14HPUtO0ilSR5sYVklcOnMr0rtHDNT3J0xPb5YLJvzMtLBNHbQJIaf/b0h6NKfocbkTyv3fsdh6oSegFzmB2mucvhuCAdAd4Rj8mDdBDZGUXzdsKL4N+1jShP6Oe3j/NVJ0Iw2QXElBMVVrjZKzdV+InvPNHLASx2XoihjBc+YHVdX6Yc52t90I7UgMd38Dr/mFKkITrWihEgPb6sqszXxY6VHgpGK84omEptX0sBiTu+g2t775A7AknFcu5mqonWB8n2Fegnf
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: pypi-credential
      namespace: test-pods
    type: Opaque

