apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: codecov-credential
  namespace: ci-furiosa-sdk
spec:
  encryptedData:
    codecov: AgAmDDk6LrHts0NPBS+FHMAsitSWOGVxolV49rJYR8zmUKFgr5j9+pzHhZl6Vfg6hQqQiPdH5Pb6uHMMwVZ81q7UoI6v7FhGv/5gD6/+e/RHjdgPYeYQA+O9lH4MOXLqFE38cE/LNyowGcBc79u0aVitudkFxOgvVFbVyjqte32C7Fnnrr3yFAcADkht/jUSVAh16b6Q5NONJqaWk4GH9bgzwe8jfwuu+dAWjA7003R2/Dv7HFOANUBpl7YyXpd4ES5ZzqB37A7FgARMZHuOupa+Qwtbz1SxNOjz+yYHzPJpBUWTnF9WwLXxSzs809+KE6YpxTyUIkeycXOpdU6dsDEG48Go13snaKjPZHerICmFmA7jvuSmJxwe7z1lVZAcPixBlNyuqIUgeLzPMuJO9DROFjrIvl/g6FobI7foFbeywCgSnvqRG8uA4nFOkHPcutGWE5cNn6WKvFiLzLll8P0NjFxmP/zR2HIsizRTa9byBubJ6o4a+fVFXSwU4bedyaQ80H9qhnkonaFyk4Kj6j7kUpwaYpgSnymkGH+yGAlHSe5fpnX2LnlifwwLW4sRQG0HcfFZekw5PUoNOBJpVCvvIC1s1x7+YpOCJTsqeRtbyghqQpeJSnIu2Z3t3NXx4vokNHtcsXktjoG/fHdzsEnBzpb07GYIslbvYVLhnSVcOIDnXvgJrb4hKfq1dgHn2LQwyU3YMGMDIIqxwvj5Y+t+y4a4Sw9+n0VyzopiDnuZunWzh64=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: codecov-credential
      namespace: ci-furiosa-sdk
    type: Opaque

