apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-bot
secrets:
- name: github-credential
- name: ecr-credential
- name: gcr-credential
imagePullSecrets:
- name: ecr-credential
- name: gcr-credential
