"""
    Furiosa AI Web Service API

    Furiosa AI Web Service API for Compiler and Model Tools  # noqa: E501

    The version of the OpenAPI document: v1alpha
    Contact: contact@furisa.ai
    Generated by: https://openapi-generator.tech
"""


import unittest

import furiosa.openapi
from furiosa.openapi.api.dss_api import DssApi  # noqa: E501


class TestDssApi(unittest.TestCase):
    """DssApi unit test stubs"""

    def setUp(self):
        self.api = DssApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_dss_v1alpha1_build_calibration_model_post(self):
        """Test case for api_dss_v1alpha1_build_calibration_model_post

        Calibrate a model and return the calibrated one  # noqa: E501
        """
        pass

    def test_api_dss_v1alpha1_quantize_post(self):
        """Test case for api_dss_v1alpha1_quantize_post

        Calibrate a model and return the calibrated one  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
