"""
    Furiosa AI Web Service API

    Furiosa AI Web Service API for Compiler and Model Tools  # noqa: E501

    The version of the OpenAPI document: v1alpha
    Contact: contact@furisa.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import furiosa.openapi
from furiosa.openapi.model.artifact_meta import ArtifactMeta


class TestArtifactMeta(unittest.TestCase):
    """ArtifactMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testArtifactMeta(self):
        """Test ArtifactMeta"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ArtifactMeta()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
