"""
    Furiosa AI Web Service API

    Furiosa AI Web Service API for Compiler and Model Tools  # noqa: E501

    The version of the OpenAPI document: v1alpha
    Contact: contact@furisa.ai
    Generated by: https://openapi-generator.tech
"""


import unittest

import furiosa.openapi
from furiosa.openapi.api.compiler_v1_api import CompilerV1Api  # noqa: E501


class TestCompilerV1Api(unittest.TestCase):
    """CompilerV1Api unit test stubs"""

    def setUp(self):
        self.api = CompilerV1Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_task(self):
        """Test case for create_task

        Compile  # noqa: E501
        """
        pass

    def test_get_artifact(self):
        """Test case for get_artifact

        Gets resources of a specific compile task  # noqa: E501
        """
        pass

    def test_get_log(self):
        """Test case for get_log

        Get compilation task log  # noqa: E501
        """
        pass

    def test_get_task(self):
        """Test case for get_task

        Get compilation task status  # noqa: E501
        """
        pass

    def test_get_toolchains(self):
        """Test case for get_toolchains

        Get compiler toolchains  # noqa: E501
        """
        pass

    def test_kill_task(self):
        """Test case for kill_task

        Kill the compilation task  # noqa: E501
        """
        pass

    def test_list_artifacts(self):
        """Test case for list_artifacts

        Gets summary of artifacts  # noqa: E501
        """
        pass

    def test_list_tasks(self):
        """Test case for list_tasks

        List compilation tasks  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
