# flake8: noqa

"""
    Furiosa AI Web Service API

    Furiosa AI Web Service API for Compiler and Model Tools  # noqa: E501

    The version of the OpenAPI document: v1alpha
    Contact: contact@furiosa.ai
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from furiosa.common.openapi.api_client import ApiClient

# import Configuration
from furiosa.common.openapi.configuration import Configuration

# import exceptions
from furiosa.common.openapi.exceptions import (
    ApiAttributeError,
    ApiException,
    ApiKeyError,
    ApiTypeError,
    ApiValueError,
    OpenApiException,
)
